# Generated by Django 3.0.6 on 2020-07-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('hbp_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HbpUser',
        ),
    ]
